### ISSUE TITLE
Face with a crash caused by [NSKeyedArchiver edo_archivedDataWithObject:]

### ISSUE THREAD

**Issue by niyaoyao** [google/eDistantObject#221]
```
[NSKeyedUnarchiver edo_unarchiveObjectWithData:]: unrecognized selector sent to class 0x7fff86d90730
 +[NSKeyedArchiver edo_archivedDataWithObject:]: unrecognized selector sent to class 0x7fff86d90758
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSKeyedArchiver edo_archivedDataWithObject:]: unrecognized selector sent to class 0x7fff86d90758'
```

Hi, all I'm facing with a crash caused by `[NSKeyedArchiver edo_archivedDataWithObject:]` with static library in Xcode 12. And the console log shows above. How can I fix it? Can anybody help?

**Comment by tirodkar** [comment]
Is this with CocoaPods and EarlGrey with the test starting and immediately crashing without the `XCUIApplication launch` being called?

**Comment by niyaoyao** [comment]
> Is this with CocoaPods and EarlGrey with the test starting and immediately crashing without the `XCUIApplication launch` being called?

Nope, the test App has been launched after build UITest Runner success. The main test App crashed when create a Socket Service connect to UITest process. And I have checked the library `libeDistantObject.a` which has been already added into link libraries in Build Phases of both the main project and UITests targets.

I'm trying to add the source files into the project manually to fix the issue. But I'm not sure what I have done is right.

**Comment by niyaoyao** [comment]
Hi, I find out the reason why the static library `libeDistantObject.a` couldn't link into the target, because I've forgot add `-ObjC` and `-fobjc-arc` flags into  Link Flags  of UI Tests Target.

Thanks for reply! Hope this will help others and I will close this issue.
